# site settings

title: dannydenovi
description: Danny De Novi online CV

# author settings

author:
  name: Danny De Novi
  email: dannydenovi@gmail.com
photo: /assets/jpg/photo.jpg

# social media links

social:
  #facebook: username
  github: dannydenovi
  instagram: dannydenovi
  #linkedin: username
  #stackoverflow: 0000000/username
  #twitter: username

# build settings

exclude:
  - LICENSE
  - README.md

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2
  - jekyll-seo-tag
  - jekyll-sitemap

whitelist:
  - jekyll-sitemap

sass:
  sass_dir: _sass
  style: compressed
  sourcemap: never

feed:
  path: atom.xml

autopages:
  enabled: false

pagination:
  enabled: true
  per_page: 1
  sort_reverse: true
  permalink: /:num/
  title: ":title &middot; Page :num"
